# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Program Files\Python\Work\movie.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 130, 54, 12))
        self.label_5.setObjectName("label_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(60, 50, 461, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.cb_ports = QtWidgets.QComboBox(self.splitter)
        self.cb_ports.setObjectName("cb_ports")
        self.te_search = QtWidgets.QTextEdit(self.splitter)
        self.te_search.setObjectName("te_search")
        self.btn_search = QtWidgets.QPushButton(self.splitter)
        self.btn_search.setObjectName("btn_search")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(60, 150, 381, 401))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.lt_results = QtWidgets.QListWidget(self.splitter_2)
        self.lt_results.setObjectName("lt_results")
        self.lt_drama = QtWidgets.QListWidget(self.splitter_2)
        self.lt_drama.setObjectName("lt_drama")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(450, 130, 75, 421))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label = QtWidgets.QLabel(self.splitter_3)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setIndent(1)
        self.label.setObjectName("label")
        self.btn_out1 = QtWidgets.QPushButton(self.splitter_3)
        self.btn_out1.setObjectName("btn_out1")
        self.btn_out2 = QtWidgets.QPushButton(self.splitter_3)
        self.btn_out2.setObjectName("btn_out2")
        self.label_2 = QtWidgets.QLabel(self.splitter_3)
        self.label_2.setObjectName("label_2")
        self.btn_down1 = QtWidgets.QPushButton(self.splitter_3)
        self.btn_down1.setObjectName("btn_down1")
        self.btn_down2 = QtWidgets.QPushButton(self.splitter_3)
        self.btn_down2.setObjectName("btn_down2")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        self.label_3.setObjectName("label_3")
        self.btn_play = QtWidgets.QPushButton(self.splitter_3)
        self.btn_play.setObjectName("btn_play")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.at_help = QtWidgets.QAction(MainWindow)
        self.at_help.setObjectName("at_help")
        self.at_about = QtWidgets.QAction(MainWindow)
        self.at_about.setObjectName("at_about")
        self.menu.addAction(self.at_help)
        self.menu.addSeparator()
        self.menu.addAction(self.at_about)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "搜索结果"))
        self.label_5.setText(_translate("MainWindow", "剧集列表"))
        self.btn_search.setText(_translate("MainWindow", "搜索"))
        self.label.setText(_translate("MainWindow", "导出"))
        self.btn_out1.setText(_translate("MainWindow", "导出选中"))
        self.btn_out2.setText(_translate("MainWindow", "导出全部"))
        self.label_2.setText(_translate("MainWindow", "下载"))
        self.btn_down1.setText(_translate("MainWindow", "下载选中"))
        self.btn_down2.setText(_translate("MainWindow", "下载全部"))
        self.label_3.setText(_translate("MainWindow", "播放"))
        self.btn_play.setText(_translate("MainWindow", "播放"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.at_help.setText(_translate("MainWindow", "帮助"))
        self.at_about.setText(_translate("MainWindow", "关于"))
